name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
  workflow_call:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        id: set-up-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install build twine

      - run: python -m build

      - run: |
          echo "# Twine check" >> $GITHUB_STEP_SUMMARY
          python -m twine check dist/* >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

      - name: Upload package distributions
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  publish-to-test:
    needs: build
    runs-on: ubuntu-latest
    #    if: "github.ref_type == 'tag'"
    environment:
      name: TestPyPI
    permissions:
      id-token: write
    steps:
      - name: Download package distributions
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/
      # using trusted publisher, no need for token
      # bug workaround:
      # WARNING  Error during upload. Retry with the --verbose option for more details.
      # ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
      #          Binary wheel 'actionlint_py-1.6.24-py2.py3-none-linux_x86_64.whl' has
      #          an unsupported platform tag 'linux_x86_64'.
      - name: Upload to test mirror
        run: |
          python -m twine upload --repository-url https://test.pypi.org/legacy/ ./dist/*.tar.gz --username __token__
#      - name: Publish package distributions to TestPyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          repository-url: https://test.pypi.org/legacy/
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}
