name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        id: set-up-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install build twine
      - run: python -m build
      - run: python -m twine check dist/*
      - name: Upload package distributions
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  publish-to-test:
    needs: build
    runs-on: ubuntu-latest
    if: "github.ref_type == 'tag'"
    environment:
      name: TestPyPI
    permissions:
      id-token: write
    steps:
      - name: Download package distributions
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist/

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
