# this job increments dev version, builds and publishes a test package
name: Build test release
on:
  pull_request:
    # only PR to main
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up Python
        id: set-up-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Increment dev version
        run: |
          python ./_custom_build/version.py --increment-dev

      - run: |
          python -m build
          VERSION=$(python ./_custom_build/version.py)
          {
          echo "# Test pip install call"
          echo '```pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ --pre actionlint-py=='"$VERSION"'```'
          } >> "$GITHUB_STEP_SUMMARY"

      - run: |
          {
          echo "# Twine check"
          python -m twine check dist/*
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload package distributions
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

      # commit only if everything succeeds
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment dev version

  publish-to-test:
    name: Publish to test Pypi
    needs: build
    uses: Mateusz-Grzelinski/actionlint-py/.github/workflows/upload-to-pypi.yml@main
    permissions:
      id-token: write
      contents: write
    with:
      upload-mirror: "https://test.pypi.org/legacy/"
    secrets:
      pypi-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
