name: Build public release
on:
  push:
    # only PR to main
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Git tag (ref) to checkout
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        description: Git tag (ref) to checkout
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Set up Python
        id: set-up-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install build twine

      - run: |
          python -m build
          VERSION=$(python ./_custom_build/version.py)
          echo "# Test pip install call"
          echo "pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ actionlint-py==$VERSION" >> $GITHUB_STEP_SUMMARY
          echo "# Release pip install call"
          echo "pip install actionlint-py==$VERSION" >> $GITHUB_STEP_SUMMARY

      - run: |
          echo "# Twine check" >> $GITHUB_STEP_SUMMARY
          python -m twine check dist/* >> $GITHUB_STEP_SUMMARY

      - name: Upload package distributions
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  publish-to-release:
    name: Publish to public Pypi
    needs: build
#    if: startsWith(github.ref, 'refs/tags') && !contains(github.ref, 'dev') && !contains(github.ref, 'release')
    uses: Mateusz-Grzelinski/actionlint-py/.github/workflows/upload.yml@main
    permissions:
      id-token: write
      contents: write
    with:
      upload-mirror: "https://pypi.org/legacy/"
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
