name: Build and optionally trigger release
on:
  pull_request:
    # only PR to main
    branches:
      - main
#  push:
#    # only tagged commit on main can trigger prod release
#    branches:
#      - main
#    tags:
#      - v*
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Git tag (ref) to checkout
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        description: Git tag to checkout
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Set up Python
        id: set-up-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Increment dev version
        if: ${{ inputs.tag }} == ''
        run: |
          python ./_custom_build/version.py --increment-dev

      - run: |
          python -m build
          VERSION=$(python ./_custom_build/version.py)
          echo "# Test pip install call"
          echo "pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ actionlint-py==$VERSION" >> $GITHUB_STEP_SUMMARY
          echo "# Release pip install call"
          echo "pip install actionlint-py==$VERSION" >> $GITHUB_STEP_SUMMARY

      - run: |
          echo "# Twine check" >> $GITHUB_STEP_SUMMARY
          python -m twine check dist/* >> $GITHUB_STEP_SUMMARY

      - name: Upload package distributions
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

      # commit only if everything succeeds
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ inputs.tag }} == ''
        with:
          commit_message: Increment dev version

  publish-to-test:
    name: Publish to test Pypi
    needs: build
    uses: Mateusz-Grzelinski/actionlint-py/.github/workflows/upload.yml@main
    permissions:
      id-token: write
      contents: write
    with:
      upload-mirror: "https://test.pypi.org/legacy/"
    secrets:
      pypi-token: ${{ secrets.TEST_PYPI_API_TOKEN }}

  publish-to-release:
    name: Publish to public Pypi
    needs: build
    if: startsWith(github.ref, 'refs/tags') && !contains(github.ref, 'dev') && !contains(github.ref, 'release')
    uses: Mateusz-Grzelinski/actionlint-py/.github/workflows/upload.yml@main
    permissions:
      id-token: write
      contents: write
    with:
      upload-mirror: "https://pypi.org/legacy/"
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
