name: Tag and release

# todo write only one tagging action
on:
  # fix for existing version should be triggered manually
  workflow_dispatch:
  # tag should automatically trigger public release based on new version of actionlint binary
  push:
    branches:
      - main
    paths:
      - _custom_build/VERSION_ACTIONLINT.txt
jobs:
  tag-relase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: EndsWith(github.ref, 'main')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Get version
        id: get-version
        run: |
          echo version=$(python ./_custom_build/version.py --release) >> $GITHUB_OUTPUT
      - name: Git tag version
        run: |
          git tag v${{ steps.get-version.outputs.version }}
          git push --tags
