name: Tag and release

on:
  # fix for existing version should be triggered manually
  workflow_dispatch:
  # tag should automatically trigger public release based on new version of actionlint binary
  push:
    branches:
      - main
    paths:
      - _custom_build/**
      - pyproject.toml
      - LICENSE
jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: EndsWith(github.ref, 'main')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            build:
              - '_custom_build/**.py'
              - pyproject.toml
              - LICENSE
            bin:
              - _custom_build/VERSION_ACTIONLINT.txt
              - _custom_build/checksums.cfg

      - name: Increment build system version, reset dev version
        if: steps.changes.outputs.build == 'true'
        run: |
          python ./_custom_build/version.py --increment-build
          python ./_custom_build/version.py --reset-dev
      - name: Get version
        id: get-version
        run: |
          echo version=$(python ./_custom_build/version.py --release) >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment build system version to ${{ steps.get-version.outputs.version }}
          tagging_message: v${{ steps.get-version.outputs.version }}
    outputs:
      version: ${{ steps.get-version.outputs.version }}

  build-and-release-to-public:
    name: Publish to public pypi
    needs: tag
    uses: Mateusz-Grzelinski/actionlint-py/.github/workflows/build-rel.yml@main
    permissions:
      id-token: write
      contents: write
    with:
      tag: v${{ needs.tag.outputs.version }}
