name: Test (tox)

on:
  pull_request:
  workflow_dispatch:

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py38"]'
      os: windows-latest
      wheel-tags: true
  main-macos:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py38"]'
      os: macos-13
      wheel-tags: true
  # todo macos arm architecture is not tested
  # todo linux arm architecture is not tested
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py38"]'
      os: ubuntu-latest
