name: Increment VERSION_BUILD_SYSTEM
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - _custom_build/**
      - '!_custom_build/VERSION*'
      - pyproject.toml
      - LICENSE
jobs:
  commit-version-build-system:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Increment build system version, reset dev version
        id: build-version
        run: |
          python ./_custom_build/version.py --increment-build
          python ./_custom_build/version.py --reset-dev
      - name: Get version
        id: get-version
        run: |
          echo version=$(python ./_custom_build/version.py --release) >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment build system version to ${{ steps.get-version.outputs.version }}
          tagging_message: v${{ steps.get-version.outputs.version }}
